version: '3.3'
services:
  mysql5:
    image: mysql:5.7
    restart: "no"
    environment:
      MYSQL_DATABASE: 
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "OA"
      # You can use whatever password you like
      MYSQL_PASSWORD: "123456!Oa"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "123456!Oa"
      # Set Timezone 
      TZ: "America/Sao_Paulo"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'

