name: Apply migrations
on:
  push:
    branches: [develop]
  workflow_dispatch:
jobs:
  apply-migrations:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef
      - name: Restore with dotnet-ef
        run: |
          export PATH=$PATH:$HOME/.dotnet/tools
          . ~/.bashrc
          dotnet tool restore
      - name: List folders
        run: ls -a
      - name: List files and folders in OA_CORE.Repository
        run: ls -a OA_Core.Repository
      - name: List files and folders in OA_CORE.Api
        run: ls -a OA_Core.Api
      - name: Apply migrations with dotnet-ef-migrations
        run: dotnet ef database update --verbose -p OA_Core.Repository/OA_Core.Repository.csproj -s OA_Core.Api/OA_Core.Api.csproj -c CoreDbContext --connection ${{secrets.CONNECTION_STRING}}
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ConnectionString: ${{secrets.CONNECTION_STRING}}
