name: Apply migrations
on:
  push:
    branches: [develop]
  workflow_dispatch:
jobs:
  run-tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
        env:
          ASPNETCORE_ENVIRONMENT: Development
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests
        run: dotnet test --no-build --verbosity normal